version: 0.2

phases:
  # setup cli
  pre_build:
    commands:
      - echo SETTING UP ENVIRONMENT
      - node -v
      - npm install --force
  # Build angular project
  build:
    commands:
      - echo BUILDING PROJECT
      - npm run build
  post_build:
    commands:
      #- aws cloudfront create-invalidation --distribution-id E3NUJ2OB9C5MF7 --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: build



